version: "3.8"

services:
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT}
    ports:
      - "${BLUE_PORT}:3000"
    networks:
      - app_network

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT}
    ports:
      - "${GREEN_PORT}:3000"
    networks:
      - app_network

  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/entrypoint.sh:/etc/nginx/entrypoint.sh
    depends_on:
      - app_blue
      - app_green
    networks:
      - app_network
    entrypoint: ["/bin/bash", "/etc/nginx/entrypoint.sh"]

networks:
  app_network:
    driver: bridge
