version: '3.8'

services:
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    ports:
      - "8081:3000"
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=3000
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    ports:
      - "8082:3000"
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=3000
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - "8080:80"
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL:-blue}
      - BLUE_PORT=8081
      - GREEN_PORT=8082
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    depends_on:
      - app_blue
      - app_green
    networks:
      - app_network
    command: >
      sh -c "envsubst '$${ACTIVE_POOL} $${BLUE_PORT} $${GREEN_PORT}' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"

networks:
  app_network:
    driver: bridge
